/**
 * Danh sách tuyến xe Nhà xe Út Chí — dùng chung cho web và RAG (đồng bộ với knowledge/nha-xe-ut-chi.md).
 * Giá/km/thời gian là tham khảo; luôn xác nhận khi đặt vé.
 */

export type BusRouteCategoryId = "bp-hcm" | "lien-tinh" | "noi-tinh";

export type BusRoute = {
  id: string;
  category: BusRouteCategoryId;
  routeVi: string;
  routeEn: string;
  distKm: string;
  durationVi: string;
  durationEn: string;
  priceVi: string;
  priceEn: string;
  vehicleVi: string;
  vehicleEn: string;
};

export const busRouteCategoryLabels: Record<
  BusRouteCategoryId,
  { titleVi: string; titleEn: string; blurbVi: string; blurbEn: string }
> = {
  "bp-hcm": {
    titleVi: "Tuyến Bình Phước ⇄ TP.HCM",
    titleEn: "Binh Phuoc ⇄ Ho Chi Minh City",
    blurbVi:
      "Đón tận nhà / điểm hẹn trong tỉnh, trả tại bến Miền Đông, khu trung tâm hoặc cổng bệnh viện theo yêu cầu.",
    blurbEn:
      "Home or agreed pickup in the province; drop-off at Mien Dong bus station, central HCMC, or hospital gates on request.",
  },
  "lien-tinh": {
    titleVi: "Tuyến liên tỉnh (không chỉ Bình Phước – HCM)",
    titleEn: "Inter-provincial (beyond Binh Phuoc – HCMC)",
    blurbVi: "Các chặng nối Đông Nam Bộ phổ biến; giờ chạy và giá theo hợp đồng từng ngày.",
    blurbEn: "Common southeastern legs; times and fares quoted per day and vehicle.",
  },
  "noi-tinh": {
    titleVi: "Tuyến nối trục trong tỉnh Bình Phước",
    titleEn: "Intra-provincial (Binh Phuoc)",
    blurbVi: "Ghép chuyến giữa các thị trấn/huyện; có thể kết hợp với tuyến đi TP.HCM.",
    blurbEn: "Connections between towns/districts; can combine with HCMC-bound services.",
  },
};

/** Danh sách đầy đủ các tuyến khai thác (một chiều được hiểu là có chiều ngược lại trừ khi ghi chú khác). */
export const allBusRoutes: BusRoute[] = [
  // —— Bình Phước ⇄ TP.HCM (theo huyện / thị trung tâm) ——
  {
    id: "dx-sg",
    category: "bp-hcm",
    routeVi: "Đồng Xoài ⇄ TP.HCM (Miền Đông / trung tâm / bệnh viện)",
    routeEn: "Dong Xoai ⇄ HCMC (Mien Dong / central / hospitals)",
    distKm: "~110 km",
    durationVi: "~2h30",
    durationEn: "~2h30",
    priceVi: "140.000đ – 180.000đ/người*",
    priceEn: "140,000 – 180,000 VND/pax*",
    vehicleVi: "Limousine 9–11 chỗ / 16 chỗ",
    vehicleEn: "9–11 seat limousine / 16-seat coach",
  },
  {
    id: "hq-sg",
    category: "bp-hcm",
    routeVi: "Hớn Quản ⇄ TP.HCM",
    routeEn: "Hon Quan ⇄ HCMC",
    distKm: "~95 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "120.000đ – 160.000đ/người*",
    priceEn: "120,000 – 160,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "dp-sg",
    category: "bp-hcm",
    routeVi: "Đồng Phú ⇄ TP.HCM",
    routeEn: "Dong Phu ⇄ HCMC",
    distKm: "~105 km",
    durationVi: "~2h15",
    durationEn: "~2h15",
    priceVi: "130.000đ – 170.000đ/người*",
    priceEn: "130,000 – 170,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "ct-sg",
    category: "bp-hcm",
    routeVi: "Chơn Thành ⇄ TP.HCM",
    routeEn: "Chon Thanh ⇄ HCMC",
    distKm: "~110 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "130.000đ – 170.000đ/người*",
    priceEn: "130,000 – 170,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "bl-sg",
    category: "bp-hcm",
    routeVi: "Bình Long ⇄ TP.HCM",
    routeEn: "Binh Long ⇄ HCMC",
    distKm: "~115 km",
    durationVi: "~2h30",
    durationEn: "~2h30",
    priceVi: "140.000đ – 180.000đ/người*",
    priceEn: "140,000 – 180,000 VND/pax*",
    vehicleVi: "Limousine / 16 chỗ",
    vehicleEn: "Limousine / 16-seat",
  },
  {
    id: "pl-sg",
    category: "bp-hcm",
    routeVi: "Phước Long (Thác Mơ) ⇄ TP.HCM",
    routeEn: "Phuoc Long (Thac Mo) ⇄ HCMC",
    distKm: "~100 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "130.000đ – 165.000đ/người*",
    priceEn: "130,000 – 165,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "bdang-sg",
    category: "bp-hcm",
    routeVi: "Bù Đăng ⇄ TP.HCM",
    routeEn: "Bu Dang ⇄ HCMC",
    distKm: "~130 km",
    durationVi: "~2h45",
    durationEn: "~2h45",
    priceVi: "150.000đ – 190.000đ/người*",
    priceEn: "150,000 – 190,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "bgm-sg",
    category: "bp-hcm",
    routeVi: "Bù Gia Mập ⇄ TP.HCM",
    routeEn: "Bu Gia Map ⇄ HCMC",
    distKm: "~165 km",
    durationVi: "~3h15",
    durationEn: "~3h15",
    priceVi: "170.000đ – 220.000đ/người*",
    priceEn: "170,000 – 220,000 VND/pax*",
    vehicleVi: "Limousine / 16 chỗ",
    vehicleEn: "Limousine / 16-seat",
  },
  {
    id: "ln-sg",
    category: "bp-hcm",
    routeVi: "Lộc Ninh ⇄ TP.HCM",
    routeEn: "Loc Ninh ⇄ HCMC",
    distKm: "~140 km",
    durationVi: "~3h",
    durationEn: "~3h",
    priceVi: "140.000đ – 210.000đ/người*",
    priceEn: "140,000 – 210,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "bdop-sg",
    category: "bp-hcm",
    routeVi: "Bù Đốp ⇄ TP.HCM",
    routeEn: "Bu Dop ⇄ HCMC",
    distKm: "~200 km",
    durationVi: "~3h30 – 5h",
    durationEn: "~3h30 – 5h",
    priceVi: "180.000đ – 250.000đ/người*",
    priceEn: "180,000 – 250,000 VND/pax*",
    vehicleVi: "Limousine / 16 chỗ",
    vehicleEn: "Limousine / 16-seat",
  },
  {
    id: "dx-tsn",
    category: "bp-hcm",
    routeVi: "Đồng Xoài ⇄ Tân Sơn Nhất (sân bay)",
    routeEn: "Dong Xoai ⇄ Tan Son Nhat (airport)",
    distKm: "~115 km",
    durationVi: "~2h30 – 3h",
    durationEn: "~2h30 – 3h",
    priceVi: "145.000đ – 190.000đ/người*",
    priceEn: "145,000 – 190,000 VND/pax*",
    vehicleVi: "Limousine (hành lý cồng kềnh báo trước)",
    vehicleEn: "Limousine (bulky luggage — advise when booking)",
  },
  // —— Liên tỉnh ——
  {
    id: "bdop-vt",
    category: "lien-tinh",
    routeVi: "Bù Đốp ⇄ Bà Rịa – Vũng Tàu",
    routeEn: "Bu Dop ⇄ Ba Ria – Vung Tau",
    distKm: "~250 km",
    durationVi: "~5h – 5h30",
    durationEn: "~5h – 5h30",
    priceVi: "280.000đ – 320.000đ/người*",
    priceEn: "280,000 – 320,000 VND/pax*",
    vehicleVi: "Limousine",
    vehicleEn: "Limousine",
  },
  {
    id: "dx-bh",
    category: "lien-tinh",
    routeVi: "Đồng Xoài ⇄ Biên Hòa (Đồng Nai)",
    routeEn: "Dong Xoai ⇄ Bien Hoa (Dong Nai)",
    distKm: "~135 km",
    durationVi: "~2h45",
    durationEn: "~2h45",
    priceVi: "150.000đ – 190.000đ/người*",
    priceEn: "150,000 – 190,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "dx-tdm",
    category: "lien-tinh",
    routeVi: "Đồng Xoài ⇄ Thủ Dầu Một (Bình Dương)",
    routeEn: "Dong Xoai ⇄ Thu Dau Mot (Binh Duong)",
    distKm: "~95 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "110.000đ – 150.000đ/người*",
    priceEn: "110,000 – 150,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "ln-tn",
    category: "lien-tinh",
    routeVi: "Lộc Ninh ⇄ Tây Ninh",
    routeEn: "Loc Ninh ⇄ Tay Ninh",
    distKm: "~75 km",
    durationVi: "~1h45",
    durationEn: "~1h45",
    priceVi: "90.000đ – 120.000đ/người*",
    priceEn: "90,000 – 120,000 VND/pax*",
    vehicleVi: "16 chỗ",
    vehicleEn: "16-seat coach",
  },
  {
    id: "dx-tn",
    category: "lien-tinh",
    routeVi: "Đồng Xoài ⇄ Tây Ninh",
    routeEn: "Dong Xoai ⇄ Tay Ninh",
    distKm: "~120 km",
    durationVi: "~2h30",
    durationEn: "~2h30",
    priceVi: "120.000đ – 160.000đ/người*",
    priceEn: "120,000 – 160,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "ct-vt",
    category: "lien-tinh",
    routeVi: "Chơn Thành ⇄ Bà Rịa – Vũng Tàu",
    routeEn: "Chon Thanh ⇄ Ba Ria – Vung Tau",
    distKm: "~220 km",
    durationVi: "~4h30 – 5h",
    durationEn: "~4h30 – 5h",
    priceVi: "250.000đ – 300.000đ/người*",
    priceEn: "250,000 – 300,000 VND/pax*",
    vehicleVi: "Limousine / 16 chỗ",
    vehicleEn: "Limousine / 16-seat",
  },
  {
    id: "pl-di-an",
    category: "lien-tinh",
    routeVi: "Phước Long ⇄ Dĩ An (Bình Dương)",
    routeEn: "Phuoc Long ⇄ Di An (Binh Duong)",
    distKm: "~100 km",
    durationVi: "~2h15",
    durationEn: "~2h15",
    priceVi: "125.000đ – 160.000đ/người*",
    priceEn: "125,000 – 160,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "ln-tdm",
    category: "lien-tinh",
    routeVi: "Lộc Ninh ⇄ Thủ Dầu Một",
    routeEn: "Loc Ninh ⇄ Thu Dau Mot",
    distKm: "~85 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "100.000đ – 140.000đ/người*",
    priceEn: "100,000 – 140,000 VND/pax*",
    vehicleVi: "16 chỗ",
    vehicleEn: "16-seat coach",
  },
  {
    id: "bdop-di-an",
    category: "lien-tinh",
    routeVi: "Bù Đốp ⇄ Dĩ An – Thuận An",
    routeEn: "Bu Dop ⇄ Di An – Thuan An",
    distKm: "~185 km",
    durationVi: "~4h",
    durationEn: "~4h",
    priceVi: "200.000đ – 260.000đ/người*",
    priceEn: "200,000 – 260,000 VND/pax*",
    vehicleVi: "Limousine / 16 chỗ",
    vehicleEn: "Limousine / 16-seat",
  },
  // —— Nội tỉnh ——
  {
    id: "dx-ln",
    category: "noi-tinh",
    routeVi: "Đồng Xoài ⇄ Lộc Ninh",
    routeEn: "Dong Xoai ⇄ Loc Ninh",
    distKm: "~80 km",
    durationVi: "~1h45",
    durationEn: "~1h45",
    priceVi: "70.000đ – 95.000đ/người*",
    priceEn: "70,000 – 95,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "dx-bdop",
    category: "noi-tinh",
    routeVi: "Đồng Xoài ⇄ Bù Đốp",
    routeEn: "Dong Xoai ⇄ Bu Dop",
    distKm: "~115 km",
    durationVi: "~2h30",
    durationEn: "~2h30",
    priceVi: "90.000đ – 120.000đ/người*",
    priceEn: "90,000 – 120,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "dx-ct",
    category: "noi-tinh",
    routeVi: "Đồng Xoài ⇄ Chơn Thành",
    routeEn: "Dong Xoai ⇄ Chon Thanh",
    distKm: "~45 km",
    durationVi: "~50 phút – 1h",
    durationEn: "~50 min – 1h",
    priceVi: "40.000đ – 60.000đ/người*",
    priceEn: "40,000 – 60,000 VND/pax*",
    vehicleVi: "Xe ghép / taxi tuyến",
    vehicleEn: "Shared van / route taxi",
  },
  {
    id: "dx-bl",
    category: "noi-tinh",
    routeVi: "Đồng Xoài ⇄ Bình Long",
    routeEn: "Dong Xoai ⇄ Binh Long",
    distKm: "~75 km",
    durationVi: "~1h30",
    durationEn: "~1h30",
    priceVi: "65.000đ – 85.000đ/người*",
    priceEn: "65,000 – 85,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "dx-pl",
    category: "noi-tinh",
    routeVi: "Đồng Xoài ⇄ Phước Long (Thác Mơ)",
    routeEn: "Dong Xoai ⇄ Phuoc Long (Thac Mo)",
    distKm: "~35 km",
    durationVi: "~40 phút",
    durationEn: "~40 min",
    priceVi: "35.000đ – 50.000đ/người*",
    priceEn: "35,000 – 50,000 VND/pax*",
    vehicleVi: "Xe ghép",
    vehicleEn: "Shared van",
  },
  {
    id: "ln-bdop",
    category: "noi-tinh",
    routeVi: "Lộc Ninh ⇄ Bù Đốp",
    routeEn: "Loc Ninh ⇄ Bu Dop",
    distKm: "~95 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "80.000đ – 110.000đ/người*",
    priceEn: "80,000 – 110,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "ct-bdop",
    category: "noi-tinh",
    routeVi: "Chơn Thành ⇄ Bù Đốp",
    routeEn: "Chon Thanh ⇄ Bu Dop",
    distKm: "~130 km",
    durationVi: "~2h45",
    durationEn: "~2h45",
    priceVi: "110.000đ – 145.000đ/người*",
    priceEn: "110,000 – 145,000 VND/pax*",
    vehicleVi: "16 chỗ / Limousine",
    vehicleEn: "16-seat / limousine",
  },
  {
    id: "hq-dx",
    category: "noi-tinh",
    routeVi: "Hớn Quản ⇄ Đồng Xoài",
    routeEn: "Hon Quan ⇄ Dong Xoai",
    distKm: "~35 km",
    durationVi: "~45 phút",
    durationEn: "~45 min",
    priceVi: "35.000đ – 50.000đ/người*",
    priceEn: "35,000 – 50,000 VND/pax*",
    vehicleVi: "Xe ghép",
    vehicleEn: "Shared van",
  },
  {
    id: "dp-dx",
    category: "noi-tinh",
    routeVi: "Đồng Phú ⇄ Đồng Xoài",
    routeEn: "Dong Phu ⇄ Dong Xoai",
    distKm: "~25 km",
    durationVi: "~35 – 45 phút",
    durationEn: "~35 – 45 min",
    priceVi: "30.000đ – 45.000đ/người*",
    priceEn: "30,000 – 45,000 VND/pax*",
    vehicleVi: "Xe ghép",
    vehicleEn: "Shared van",
  },
  {
    id: "bgm-dx",
    category: "noi-tinh",
    routeVi: "Bù Gia Mập ⇄ Đồng Xoài",
    routeEn: "Bu Gia Map ⇄ Dong Xoai",
    distKm: "~95 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "80.000đ – 110.000đ/người*",
    priceEn: "80,000 – 110,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "bdang-ct",
    category: "noi-tinh",
    routeVi: "Bù Đăng ⇄ Chơn Thành",
    routeEn: "Bu Dang ⇄ Chon Thanh",
    distKm: "~70 km",
    durationVi: "~1h30",
    durationEn: "~1h30",
    priceVi: "60.000đ – 85.000đ/người*",
    priceEn: "60,000 – 85,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "pl-ln",
    category: "noi-tinh",
    routeVi: "Phước Long ⇄ Lộc Ninh",
    routeEn: "Phuoc Long ⇄ Loc Ninh",
    distKm: "~95 km",
    durationVi: "~2h",
    durationEn: "~2h",
    priceVi: "75.000đ – 100.000đ/người*",
    priceEn: "75,000 – 100,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
  {
    id: "bl-ct",
    category: "noi-tinh",
    routeVi: "Bình Long ⇄ Chơn Thành",
    routeEn: "Binh Long ⇄ Chon Thanh",
    distKm: "~55 km",
    durationVi: "~1h15",
    durationEn: "~1h15",
    priceVi: "50.000đ – 70.000đ/người*",
    priceEn: "50,000 – 70,000 VND/pax*",
    vehicleVi: "Xe ghép",
    vehicleEn: "Shared van",
  },
  {
    id: "hq-ct",
    category: "noi-tinh",
    routeVi: "Hớn Quản ⇄ Chơn Thành",
    routeEn: "Hon Quan ⇄ Chon Thanh",
    distKm: "~65 km",
    durationVi: "~1h20",
    durationEn: "~1h20",
    priceVi: "55.000đ – 75.000đ/người*",
    priceEn: "55,000 – 75,000 VND/pax*",
    vehicleVi: "Xe ghép",
    vehicleEn: "Shared van",
  },
  {
    id: "bdang-pl",
    category: "noi-tinh",
    routeVi: "Bù Đăng ⇄ Phước Long",
    routeEn: "Bu Dang ⇄ Phuoc Long",
    distKm: "~85 km",
    durationVi: "~1h50",
    durationEn: "~1h50",
    priceVi: "70.000đ – 95.000đ/người*",
    priceEn: "70,000 – 95,000 VND/pax*",
    vehicleVi: "Xe ghép / 16 chỗ",
    vehicleEn: "Shared van / 16-seat",
  },
];

/** Số bản ghi trong `allBusRoutes` (đồng bộ web + RAG). */
export const busRouteCount = allBusRoutes.length;

export function routesByCategory(cat: BusRouteCategoryId): BusRoute[] {
  return allBusRoutes.filter((r) => r.category === cat);
}
